#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    ddev-drupal-11-canvas-accounts-phpmyadmin-80-http:
      entrypoints:
        - http-8036
      rule: HostRegexp(`^ddev-drupal-11-canvas-accounts\.ddev\.site$`)
      
      service: "ddev-drupal-11-canvas-accounts-phpmyadmin-80"
      tls: false
      # middlewares:
      #   - "ddev-drupal-11-canvas-accounts-redirectHttps"
    ddev-drupal-11-canvas-accounts-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^ddev-drupal-11-canvas-accounts\.ddev\.site$`)
      
      service: "ddev-drupal-11-canvas-accounts-web-80"
      tls: false
      # middlewares:
      #   - "ddev-drupal-11-canvas-accounts-redirectHttps"
    ddev-drupal-11-canvas-accounts-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^ddev-drupal-11-canvas-accounts\.ddev\.site$`)
      
      service: "ddev-drupal-11-canvas-accounts-web-8025"
      tls: false
      # middlewares:
      #   - "ddev-drupal-11-canvas-accounts-redirectHttps"
    ddev-drupal-11-canvas-accounts-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^ddev-drupal-11-canvas-accounts\.ddev\.site$`)
      
      service: "ddev-drupal-11-canvas-accounts-xhgui-80"
      tls: false
      # middlewares:
      #   - "ddev-drupal-11-canvas-accounts-redirectHttps"
    
    
    ddev-drupal-11-canvas-accounts-phpmyadmin-80-https:
      entrypoints:
        - http-8037
      rule: HostRegexp(`^ddev-drupal-11-canvas-accounts\.ddev\.site$`)
      
      service: "ddev-drupal-11-canvas-accounts-phpmyadmin-80"
      
      tls: true
      
    
    
    ddev-drupal-11-canvas-accounts-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^ddev-drupal-11-canvas-accounts\.ddev\.site$`)
      
      service: "ddev-drupal-11-canvas-accounts-web-80"
      
      tls: true
      
    ddev-drupal-11-canvas-accounts-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^ddev-drupal-11-canvas-accounts\.ddev\.site$`)
      
      service: "ddev-drupal-11-canvas-accounts-web-8025"
      
      tls: true
      
    
    ddev-drupal-11-canvas-accounts-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^ddev-drupal-11-canvas-accounts\.ddev\.site$`)
      
      service: "ddev-drupal-11-canvas-accounts-xhgui-80"
      
      tls: true
      
    

  middlewares:
    ddev-drupal-11-canvas-accounts-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    ddev-drupal-11-canvas-accounts-phpmyadmin-80:
      loadbalancer:
        servers:
          - url: http://ddev-ddev-drupal-11-canvas-accounts-phpmyadmin:80
        
    
    ddev-drupal-11-canvas-accounts-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-ddev-drupal-11-canvas-accounts-web:80
        
    ddev-drupal-11-canvas-accounts-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-ddev-drupal-11-canvas-accounts-web:8025
        
    
    
    ddev-drupal-11-canvas-accounts-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-ddev-drupal-11-canvas-accounts-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/ddev-drupal-11-canvas-accounts.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/ddev-drupal-11-canvas-accounts.key